name: slds_app1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

# --- DEPENDENCIES GO HERE ---
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  
  # Packages
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  image_picker: ^1.0.7

  flutter_facebook_auth: ^6.0.4
# --- DEV DEPENDENCIES ---
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Icon & Splash Screen Generators
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4

# --- FLUTTER SETTINGS ---
flutter:
  uses-material-design: true

  assets:
     - assets/logo.png
     - assets/google.png
     - assets/facebook.png
     - assets/app_icon.png
     - assets/splash_logo.png

# --- APP ICON CONFIGURATION ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_icon.png"

# --- SPLASH SCREEN CONFIGURATION ---
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash_logo.png"
  android_12:
    image: "assets/splash_logo.png"
    icon_background_color: "#FFFFFF"